import { getDb } from "./db.js";
import { normalizeTitle } from "./lib/match.js";
import { deriveDifficulty } from "./lib/difficulty.js";

/**
 * DEMO=1 seed data: a realistic spread of games so the UI and every
 * recommendation mode can be exercised without any API keys.
 */

interface DemoGame {
  title: string;
  store: "steam" | "epic" | "both";
  playtime: number; // minutes
  metacritic: number | null;
  steamPct?: number;
  steamCount?: number;
  main: number | null;
  extra?: number;
  completionist?: number;
  released: string;
  genres: string[];
  tags: string[];
}

const DEMO_GAMES: DemoGame[] = [
  {
    title: "Hades",
    store: "both",
    playtime: 90,
    metacritic: 93,
    steamPct: 98,
    steamCount: 250000,
    main: 21,
    extra: 44,
    completionist: 96,
    released: "2020-09-17",
    genres: ["Action", "RPG", "Indie"],
    tags: ["Roguelite", "Difficult", "Story Rich"],
  },
  {
    title: "Portal 2",
    store: "steam",
    playtime: 0,
    metacritic: 95,
    steamPct: 98,
    steamCount: 400000,
    main: 8.5,
    extra: 13,
    completionist: 21,
    released: "2011-04-18",
    genres: ["Puzzle", "Adventure"],
    tags: ["Story Rich", "Co-op", "Funny"],
  },
  {
    title: "The Witcher 3: Wild Hunt",
    store: "steam",
    playtime: 300,
    metacritic: 92,
    steamPct: 96,
    steamCount: 700000,
    main: 51,
    extra: 103,
    completionist: 173,
    released: "2015-05-18",
    genres: ["RPG", "Adventure"],
    tags: ["Open World", "Story Rich", "Atmospheric"],
  },
  {
    title: "Celeste",
    store: "steam",
    playtime: 30,
    metacritic: 92,
    steamPct: 97,
    steamCount: 80000,
    main: 8,
    extra: 12,
    completionist: 37,
    released: "2018-01-25",
    genres: ["Platformer", "Indie"],
    tags: ["Difficult", "Precision", "Pixel Graphics"],
  },
  {
    title: "Stardew Valley",
    store: "steam",
    playtime: 4000,
    metacritic: 89,
    steamPct: 98,
    steamCount: 600000,
    main: 52,
    extra: 96,
    completionist: 156,
    released: "2016-02-26",
    genres: ["Simulation", "RPG", "Indie"],
    tags: ["Relaxing", "Farming Sim", "Cozy"],
  },
  {
    title: "Dark Souls III",
    store: "steam",
    playtime: 60,
    metacritic: 89,
    steamPct: 94,
    steamCount: 200000,
    main: 32,
    extra: 49,
    completionist: 105,
    released: "2016-04-11",
    genres: ["Action", "RPG"],
    tags: ["Souls-like", "Difficult", "Dark Fantasy"],
  },
  {
    title: "Firewatch",
    store: "steam",
    playtime: 0,
    metacritic: 81,
    steamPct: 92,
    steamCount: 60000,
    main: 4,
    extra: 5,
    completionist: 7,
    released: "2016-02-09",
    genres: ["Adventure", "Indie"],
    tags: ["Walking Simulator", "Story Rich", "Atmospheric"],
  },
  {
    title: "Control",
    store: "epic",
    playtime: 0,
    metacritic: 82,
    main: 12,
    extra: 19,
    completionist: 27,
    released: "2019-08-27",
    genres: ["Action", "Adventure"],
    tags: ["Supernatural", "Story Rich", "Third Person"],
  },
  {
    title: "Alan Wake 2",
    store: "epic",
    playtime: 0,
    metacritic: 89,
    main: 17,
    extra: 24,
    completionist: 31,
    released: "2023-10-27",
    genres: ["Action", "Adventure"],
    tags: ["Survival Horror", "Story Rich", "Atmospheric"],
  },
  {
    title: "Slay the Spire",
    store: "steam",
    playtime: 1500,
    metacritic: 89,
    steamPct: 97,
    steamCount: 120000,
    main: 24,
    extra: 70,
    completionist: 194,
    released: "2019-01-23",
    genres: ["Card", "Strategy", "Indie"],
    tags: ["Roguelike", "Deckbuilding", "Turn-Based"],
  },
  {
    title: "Outer Wilds",
    store: "epic",
    playtime: 15,
    metacritic: 85,
    main: 17,
    extra: 22,
    completionist: 28,
    released: "2019-05-28",
    genres: ["Adventure", "Indie"],
    tags: ["Exploration", "Space", "Mystery"],
  },
  {
    title: "Vampire Survivors",
    store: "steam",
    playtime: 45,
    metacritic: 87,
    steamPct: 98,
    steamCount: 250000,
    main: 17,
    extra: 40,
    completionist: 76,
    released: "2022-10-20",
    genres: ["Action", "Casual", "Indie"],
    tags: ["Roguelite", "Casual", "Pixel Graphics"],
  },
  {
    title: "Sekiro: Shadows Die Twice",
    store: "steam",
    playtime: 0,
    metacritic: 90,
    steamPct: 95,
    steamCount: 300000,
    main: 30,
    extra: 44,
    completionist: 69,
    released: "2019-03-22",
    genres: ["Action", "Adventure"],
    tags: ["Souls-like", "Difficult", "Ninja"],
  },
  {
    title: "Disco Elysium",
    store: "steam",
    playtime: 100,
    metacritic: 91,
    steamPct: 95,
    steamCount: 90000,
    main: 22,
    extra: 32,
    completionist: 48,
    released: "2019-10-15",
    genres: ["RPG", "Adventure"],
    tags: ["Story Rich", "Point and Click", "Detective"],
  },
  {
    title: "A Short Hike",
    store: "epic",
    playtime: 0,
    metacritic: 88,
    main: 1.7,
    extra: 2.5,
    completionist: 4.4,
    released: "2019-07-30",
    genres: ["Adventure", "Indie", "Casual"],
    tags: ["Relaxing", "Cozy", "Exploration"],
  },
  {
    title: "Deep Rock Galactic",
    store: "steam",
    playtime: 600,
    metacritic: 85,
    steamPct: 97,
    steamCount: 200000,
    main: null,
    released: "2020-05-13",
    genres: ["Action", "Shooter"],
    tags: ["Co-op", "Mining", "Funny"],
  },
  {
    title: "Return of the Obra Dinn",
    store: "steam",
    playtime: 0,
    metacritic: 89,
    steamPct: 96,
    steamCount: 30000,
    main: 8.5,
    extra: 10.5,
    completionist: 13,
    released: "2018-10-18",
    genres: ["Puzzle", "Adventure", "Indie"],
    tags: ["Detective", "Mystery", "Story Rich"],
  },
  {
    title: "Cuphead",
    store: "steam",
    playtime: 20,
    metacritic: 88,
    steamPct: 95,
    steamCount: 100000,
    main: 11,
    extra: 15.5,
    completionist: 27,
    released: "2017-09-29",
    genres: ["Platformer", "Action", "Indie"],
    tags: ["Difficult", "Bullet Hell", "Cartoon"],
  },
  {
    title: "Half-Life 2",
    store: "steam",
    playtime: 0,
    metacritic: 96,
    steamPct: 97,
    steamCount: 150000,
    main: 13,
    extra: 15.5,
    completionist: 21,
    released: "2004-11-16",
    genres: ["Shooter", "Action"],
    tags: ["Story Rich", "Sci-fi", "Classic"],
  },
  {
    title: "Baldur's Gate 3",
    store: "steam",
    playtime: 30,
    metacritic: 96,
    steamPct: 96,
    steamCount: 500000,
    main: 72,
    extra: 118,
    completionist: 202,
    released: "2023-08-03",
    genres: ["RPG", "Strategy"],
    tags: ["Story Rich", "Turn-Based", "Fantasy"],
  },
  {
    title: "Untitled Goose Game",
    store: "epic",
    playtime: 0,
    metacritic: 81,
    main: 3,
    extra: 4.5,
    completionist: 8,
    released: "2019-09-20",
    genres: ["Puzzle", "Indie", "Casual"],
    tags: ["Funny", "Casual", "Stealth"],
  },
  {
    title: "Lorelei and the Laser Eyes",
    store: "steam",
    playtime: 0,
    metacritic: 91,
    steamPct: 92,
    steamCount: 4000,
    main: 13.5,
    extra: 16,
    completionist: 18.5,
    released: "2024-05-16",
    genres: ["Puzzle", "Adventure", "Indie"],
    tags: ["Mystery", "Story Rich", "Surreal"],
  },
];

export function seedDemoData(): number {
  const db = getDb();
  const count = (db.prepare("SELECT COUNT(*) AS n FROM games").get() as { n: number }).n;
  if (count > 0) return 0;

  const insert = db.prepare(`
    INSERT INTO games (
      title, normalized_title, store, steam_appid, playtime_minutes,
      metacritic, steam_review_pct, steam_review_count,
      hltb_main, hltb_extra, hltb_completionist,
      difficulty, genres, tags, release_date, cover_url,
      enrich_status, last_synced
    ) VALUES (
      @title, @norm, @store, NULL, @playtime,
      @metacritic, @steamPct, @steamCount,
      @main, @extra, @completionist,
      @difficulty, @genres, @tags, @released, NULL,
      'done', @now
    )
  `);
  const now = new Date().toISOString();
  const tx = db.transaction(() => {
    for (const g of DEMO_GAMES) {
      insert.run({
        title: g.title,
        norm: normalizeTitle(g.title),
        store: g.store,
        playtime: g.playtime,
        metacritic: g.metacritic,
        steamPct: g.steamPct ?? null,
        steamCount: g.steamCount ?? null,
        main: g.main,
        extra: g.extra ?? null,
        completionist: g.completionist ?? null,
        difficulty: deriveDifficulty(g.genres, g.tags),
        genres: JSON.stringify(g.genres),
        tags: JSON.stringify(g.tags),
        released: g.released,
        now,
      });
    }
  });
  tx();
  return DEMO_GAMES.length;
}
